name: Deploy to Supabase

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency:
  group: deploy-supabase
  cancel-in-progress: true

jobs:
  deploy-db:
    name: Apply database migrations
    runs-on: ubuntu-latest
    needs: [ verify-frontend ]
    permissions:
      contents: read
    env:
      SUPABASE_PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1

      - name: Link Supabase project
        run: supabase link --project-ref "$SUPABASE_PROJECT_REF"
        working-directory: .
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Push database migrations to remote
        run: supabase db push --include-all
        working-directory: .
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

  verify-frontend:
    name: Build frontend (sanity)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend-app/package-lock.json

      - name: Install deps
        working-directory: frontend-app
        run: npm ci

      - name: Build
        working-directory: frontend-app
        run: npm run build
